package printclient

import (
	"sync"
	"time"

	"github.com/gofiber/websocket/v2"
)

// Message types used by WebSocket service
type (
	// AuthMessage represents authentication data from the client
	AuthMessage struct {
		Type          string `json:"type"`           // Message type (e.g., "auth")
		Token         string `json:"token"`          // Unique token generated by the client
		Processor     string `json:"processor"`      // Machine's processor details
		Platform      string `json:"platform"`       // Machine's platform details (e.g., OS)
		HardwareID    string `json:"hardware_id"`    // Unique hardware identifier
		ClientVersion string `json:"client_version"` // Client Software Version
	}

	// UndeliveredMsg represents a message that couldn't be delivered
	UndeliveredMsg struct {
		UserUUID  string
		Message   string
		Timestamp time.Time
		Delivered bool
	}

	// Subscription represents a WebSocket client subscription
	Subscription struct {
		ChannelName string
		UserUUID    string
		Conn        *websocket.Conn
		MessageChan chan []byte // Message channel for each connection
		Closed      bool
		Mutex       sync.Mutex
	}

	// WeightDimSubscription represents a weight/dimension machine subscription
	WeightDimSubscription struct {
		PrinterID string
		UserID    string
	}

	// Unsubscription represents an unsubscribe request
	Unsubscription struct {
		ChannelName string
		UserUUID    string
	}

	// BroadcastMsg represents a message to be broadcast to a specific channel/user
	BroadcastMsg struct {
		Channel  string
		UserUUID string
		Message  string
	}

	// ChannelMsg represents a message sent through internal channels (replaces RabbitMQ)
	ChannelMsg struct {
		Channel  string
		UserUUID string
		Message  string
	}

	// UpstreamMsg represents a log message to be sent upstream
	UpstreamMsg struct {
		ID              string
		Type            string
		Event           string
		JobID           string
		Message         string
		ClientVersion   string
		WeightMachineID string
	}

	// ClientJob represents a job message from the client
	ClientJob struct {
		JobID   string `json:"JobId"`
		Event   string `json:"Event"`
		Message string `json:"Message"`
	}

	// PrintJob represents a print job to be sent to a client
	PrintJob struct {
		PrinterID string  `json:"printer_id"`
		JobID     string  `json:"job_id"`
		JobToken  string  `json:"job_token"`
		Command   string  `json:"command"`
		Width     float64 `json:"width"`
		Height    float64 `json:"height"`
		Unit      string  `json:"unit"`
		Barcode   string  `json:"barcode"`
		Mashul    string  `json:"mashul"`
		Weight    string  `json:"weight"`
	}
)
