export type CountryProp = {
    label: string;
    code: string;
    phone_code: string;
    phoneLength?: number | number[];
    min?: number;
    max?: number;
};

export interface CountryPhoneCodeMap {
    [key: string]: CountryProp;
}



const countries: CountryProp[] = [
    { code: 'AD', label: 'Andorra', phone_code: '376', phoneLength: 6 },
    { code: 'AE', label: 'United Arab Emirates', phone_code: '971', phoneLength: 9 },
    { code: 'AF', label: 'Afghanistan', phone_code: '93', phoneLength: 9 },
    { code: 'AG', label: 'Antigua and Barbuda', phone_code: '1-268', phoneLength: 10 },
    { code: 'AI', label: 'Anguilla', phone_code: '1-264', phoneLength: 10 },
    { code: 'AL', label: 'Albania', phone_code: '355', phoneLength: 9 },
    { code: 'AM', label: 'Armenia', phone_code: '374', phoneLength: 6 },
    { code: 'AO', label: 'Angola', phone_code: '244', phoneLength: 9 },
    { code: 'AQ', label: 'Antarctica', phone_code: '672', phoneLength: 6 },
    { code: 'AR', label: 'Argentina', phone_code: '54', phoneLength: [6, 7, 8] },
    { code: 'AS', label: 'American Samoa', phone_code: '1-684', phoneLength: 10 },
    { code: 'AT', label: 'Austria', phone_code: '43', phoneLength: [10, 11] },
    { code: 'AU', label: 'Australia', phone_code: '61', phoneLength: 9 },
    { code: 'AW', label: 'Aruba', phone_code: '297', phoneLength: 7 },
    { code: 'AX', label: 'Alland Islands', phone_code: '358', min: 7, max: 10 },
    { code: 'AZ', label: 'Azerbaijan', phone_code: '994', phoneLength: 9 },
    { code: 'BA', label: 'Bosnia and Herzegovina', phone_code: '387', phoneLength: 8 },
    { code: 'BB', label: 'Barbados', phone_code: '1-246', phoneLength: 10 },
    { code: 'BD', label: 'Bangladesh', phone_code: '880', phoneLength: 10 },
    { code: 'BE', label: 'Belgium', phone_code: '32', phoneLength: 9 },
    { code: 'BF', label: 'Burkina Faso', phone_code: '226', phoneLength: 8 },
    { code: 'BG', label: 'Bulgaria', phone_code: '359', phoneLength: 9 },
    { code: 'BH', label: 'Bahrain', phone_code: '973', phoneLength: 8 },
    { code: 'BI', label: 'Burundi', phone_code: '257', phoneLength: 8 },
    { code: 'BJ', label: 'Benin', phone_code: '229', phoneLength: 8 },
    { code: 'BL', label: 'Saint Barthelemy', phone_code: '590', phoneLength: 9 },
    { code: 'BM', label: 'Bermuda', phone_code: '1-441', phoneLength: 10 },
    { code: 'BN', label: 'Brunei Darussalam', phone_code: '673', phoneLength: 7 },
    { code: 'BO', label: 'Bolivia', phone_code: '591', phoneLength: 9 },
    { code: 'BR', label: 'Brazil', phone_code: '55', phoneLength: 11 },
    { code: 'BS', label: 'Bahamas', phone_code: '1-242', phoneLength: 10 },
    { code: 'BT', label: 'Bhutan', phone_code: '975', phoneLength: 7 },
    { code: 'BV', label: 'Bouvet Island', phone_code: '47', phoneLength: 10 },
    { code: 'BW', label: 'Botswana', phone_code: '267', phoneLength: 7 },
    { code: 'BY', label: 'Belarus', phone_code: '375', phoneLength: 9 },
    { code: 'BZ', label: 'Belize', phone_code: '501', phoneLength: 7 },
    { code: 'CA', label: 'Canada', phone_code: '1', phoneLength: 10 },
    { code: 'CC', label: 'Cocos (Keeling) Islands', phone_code: '61', phoneLength: 10 },
    { code: 'CD', label: 'Congo, Democratic Republic of the', phone_code: '243', phoneLength: 7 },
    { code: 'CF', label: 'Central African Republic', phone_code: '236', phoneLength: 8 },
    { code: 'CG', label: 'Congo, Republic of the', phone_code: '242', phoneLength: 9 },
    { code: 'CH', label: 'Switzerland', phone_code: '41', phoneLength: 9 },
    { code: 'CI', label: "Cote d'Ivoire", phone_code: '225', phoneLength: 8 },
    { code: 'CK', label: 'Cook Islands', phone_code: '682', phoneLength: 5 },
    { code: 'CL', label: 'Chile', phone_code: '56', phoneLength: 9 },
    { code: 'CM', label: 'Cameroon', phone_code: '237', phoneLength: 9 },
    { code: 'CN', label: 'China', phone_code: '86', phoneLength: 11 },
    { code: 'CO', label: 'Colombia', phone_code: '57', phoneLength: 10 },
    { code: 'CR', label: 'Costa Rica', phone_code: '506', phoneLength: 8 },
    { code: 'CU', label: 'Cuba', phone_code: '53', phoneLength: 8 },
    { code: 'CV', label: 'Cape Verde', phone_code: '238', phoneLength: 7 },
    { code: 'CW', label: 'Curacao', phone_code: '599', phoneLength: 7 },
    { code: 'CX', label: 'Christmas Island', phone_code: '61', phoneLength: 9 },
    { code: 'CY', label: 'Cyprus', phone_code: '357', phoneLength: 8 },
    { code: 'CZ', label: 'Czech Republic', phone_code: '420', phoneLength: 9 },
    { code: 'DE', label: 'Germany', phone_code: '49', phoneLength: 10 },
    { code: 'DJ', label: 'Djibouti', phone_code: '253', phoneLength: 10 },
    { code: 'DK', label: 'Denmark', phone_code: '45', phoneLength: 8 },
    { code: 'DM', label: 'Dominica', phone_code: '1-767', phoneLength: 10 },
    { code: 'DO', label: 'Dominican Republic', phone_code: '1-809', phoneLength: 10 },
    { code: 'DZ', label: 'Algeria', phone_code: '213', phoneLength: 9 },
    { code: 'EC', label: 'Ecuador', phone_code: '593', phoneLength: 9 },
    { code: 'EE', label: 'Estonia', phone_code: '372', phoneLength: 8 },
    { code: 'EG', label: 'Egypt', phone_code: '20', phoneLength: 10 },
    { code: 'EH', label: 'Western Sahara', phone_code: '212', phoneLength: 9 },
    { code: 'ER', label: 'Eritrea', phone_code: '291', phoneLength: 7 },
    { code: 'ES', label: 'Spain', phone_code: '34', phoneLength: 9 },
    { code: 'ET', label: 'Ethiopia', phone_code: '251', phoneLength: 9 },
    { code: 'FI', label: 'Finland', phone_code: '358', min: 9, max: 11 },
    { code: 'FJ', label: 'Fiji', phone_code: '679', phoneLength: 7 },
    { code: 'FK', label: 'Falkland Islands (Malvinas)', phone_code: '500', phoneLength: 5 },
    { code: 'FM', label: 'Micronesia, Federated States of', phone_code: '691', phoneLength: 7 },
    { code: 'FO', label: 'Faroe Islands', phone_code: '298', phoneLength: 5 },
    { code: 'FR', label: 'France', phone_code: '33', phoneLength: 9 },
    { code: 'GA', label: 'Gabon', phone_code: '241', phoneLength: 7 },
    { code: 'GB', label: 'United Kingdom', phone_code: '44', phoneLength: 10 },
    { code: 'GD', label: 'Grenada', phone_code: '1-473', phoneLength: 10 },
    { code: 'GE', label: 'Georgia', phone_code: '995', phoneLength: 9 },
    { code: 'GF', label: 'French Guiana', phone_code: '594', phoneLength: 9 },
    { code: 'GG', label: 'Guernsey', phone_code: '44', phoneLength: 10 },
    { code: 'GH', label: 'Ghana', phone_code: '233', phoneLength: 9 },
    { code: 'GI', label: 'Gibraltar', phone_code: '350', phoneLength: 8 },
    { code: 'GL', label: 'Greenland', phone_code: '299', phoneLength: 6 },
    { code: 'GM', label: 'Gambia', phone_code: '220', phoneLength: 7 },
    { code: 'GN', label: 'Guinea', phone_code: '224', phoneLength: 9 },
    { code: 'GP', label: 'Guadeloupe', phone_code: '590', phoneLength: 9 },
    { code: 'GQ', label: 'Equatorial Guinea', phone_code: '240', phoneLength: 9 },
    { code: 'GR', label: 'Greece', phone_code: '30', phoneLength: 10 },
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone_code: '500', phoneLength: 5 },
    { code: 'GT', label: 'Guatemala', phone_code: '502', phoneLength: 8 },
    { code: 'GU', label: 'Guam', phone_code: '1-671', phoneLength: 10 },
    { code: 'GW', label: 'Guinea-Bissau', phone_code: '245', phoneLength: 9 },
    { code: 'GY', label: 'Guyana', phone_code: '592', phoneLength: 7 },
    { code: 'HK', label: 'Hong Kong', phone_code: '852', phoneLength: 8 },
    { code: 'HM', label: 'Heard Island and McDonald Islands', phone_code: '672', phoneLength: 10 },
    { code: 'HN', label: 'Honduras', phone_code: '504', phoneLength: 8 },
    { code: 'HR', label: 'Croatia', phone_code: '385', phoneLength: 9 },
    { code: 'HT', label: 'Haiti', phone_code: '509', phoneLength: 8 },
    { code: 'HU', label: 'Hungary', phone_code: '36', phoneLength: 9 },
    { code: 'ID', label: 'Indonesia', phone_code: '62', phoneLength: 11 },
    { code: 'IE', label: 'Ireland', phone_code: '353', phoneLength: 9 },
    { code: 'IL', label: 'Israel', phone_code: '972', phoneLength: 9 },
    { code: 'IM', label: 'Isle of Man', phone_code: '44', phoneLength: 10 },
    { code: 'IN', label: 'India', phone_code: '91', phoneLength: 10 },
    { code: 'IO', label: 'British Indian Ocean Territory', phone_code: '246', phoneLength: 7 },
    { code: 'IQ', label: 'Iraq', phone_code: '964', phoneLength: 10 },
    { code: 'IR', label: 'Iran, Islamic Republic of', phone_code: '98', phoneLength: 11 },
    { code: 'IS', label: 'Iceland', phone_code: '354', phoneLength: 7 },
    { code: 'IT', label: 'Italy', phone_code: '39', phoneLength: 10 },
    { code: 'JE', label: 'Jersey', phone_code: '44', phoneLength: 10 },
    { code: 'JM', label: 'Jamaica', phone_code: '1-876', phoneLength: 10 },
    { code: 'JO', label: 'Jordan', phone_code: '962', phoneLength: [8, 9] },
    { code: 'JP', label: 'Japan', phone_code: '81' },
    { code: 'KE', label: 'Kenya', phone_code: '254', phoneLength: 10 },
    { code: 'KG', label: 'Kyrgyzstan', phone_code: '996', phoneLength: 9 },
    { code: 'KH', label: 'Cambodia', phone_code: '855', phoneLength: 9 },
    { code: 'KI', label: 'Kiribati', phone_code: '686', phoneLength: 8 },
    { code: 'KM', label: 'Comoros', phone_code: '269', phoneLength: 7 },
    { code: 'KN', label: 'Saint Kitts and Nevis', phone_code: '1-869', phoneLength: 10 },
    { code: 'KP', label: "Korea, Democratic People's Republic of", phone_code: '850', phoneLength: [4, 6, 7, 13] },
    { code: 'KR', label: 'Korea, Republic of', phone_code: '82', phoneLength: [7, 8] },
    { code: 'KW', label: 'Kuwait', phone_code: '965', phoneLength: 8 },
    { code: 'KY', label: 'Cayman Islands', phone_code: '1-345', phoneLength: 7 },
    { code: 'KZ', label: 'Kazakhstan', phone_code: '7', phoneLength: 10 },
    { code: 'LA', label: "Lao People's Democratic Republic", phone_code: '856', phoneLength: [8, 9] },
    { code: 'LB', label: 'Lebanon', phone_code: '961', phoneLength: [7, 8] },
    { code: 'LC', label: 'Saint Lucia', phone_code: '1-758', phoneLength: 7 },
    { code: 'LI', label: 'Liechtenstein', phone_code: '423', phoneLength: 7 },
    { code: 'LK', label: 'Sri Lanka', phone_code: '94', phoneLength: 7 },
    { code: 'LR', label: 'Liberia', phone_code: '231', phoneLength: [8, 9] },
    { code: 'LS', label: 'Lesotho', phone_code: '266', phoneLength: 8 },
    { code: 'LT', label: 'Lithuania', phone_code: '370', phoneLength: 8 },
    { code: 'LU', label: 'Luxembourg', phone_code: '352', phoneLength: 9 },
    { code: 'LV', label: 'Latvia', phone_code: '371', phoneLength: 8 },
    { code: 'LY', label: 'Libya', phone_code: '218', phoneLength: 10 },
    { code: 'MA', label: 'Morocco', phone_code: '212', phoneLength: 9 },
    { code: 'MC', label: 'Monaco', phone_code: '377', phoneLength: 8 },
    { code: 'MD', label: 'Moldova, Republic of', phone_code: '373', phoneLength: 8 },
    { code: 'ME', label: 'Montenegro', phone_code: '382', phoneLength: 8 },
    { code: 'MF', label: 'Saint Martin (French part)', phone_code: '590', phoneLength: 6 },
    { code: 'MG', label: 'Madagascar', phone_code: '261', phoneLength: 7 },
    { code: 'MH', label: 'Marshall Islands', phone_code: '692', phoneLength: 7 },
    { code: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', phone_code: '389', phoneLength: 8 },
    { code: 'ML', label: 'Mali', phone_code: '223', phoneLength: 8 },
    { code: 'MM', label: 'Myanmar', phone_code: '95', min: 7, max: 10 },
    { code: 'MN', label: 'Mongolia', phone_code: '976', phoneLength: 8 },
    { code: 'MO', label: 'Macao', phone_code: '853', phoneLength: 8 },
    { code: 'MP', label: 'Northern Mariana Islands', phone_code: '1-670', phoneLength: 7 },
    { code: 'MQ', label: 'Martinique', phone_code: '596', phoneLength: 9 },
    { code: 'MR', label: 'Mauritania', phone_code: '222', phoneLength: 8 },
    { code: 'MS', label: 'Montserrat', phone_code: '1-664', phoneLength: 10 },
    { code: 'MT', label: 'Malta', phone_code: '356', phoneLength: 8 },
    { code: 'MU', label: 'Mauritius', phone_code: '230', phoneLength: 8 },
    { code: 'MV', label: 'Maldives', phone_code: '960', phoneLength: 7 },
    { code: 'MW', label: 'Malawi', phone_code: '265', phoneLength: [7, 8, 9] },
    { code: 'MX', label: 'Mexico', phone_code: '52', phoneLength: 10 },
    { code: 'MY', label: 'Malaysia', phone_code: '60', phoneLength: 7 },
    { code: 'MZ', label: 'Mozambique', phone_code: '258', phoneLength: 12 },
    { code: 'NA', label: 'Namibia', phone_code: '264', phoneLength: 7 },
    { code: 'NC', label: 'New Caledonia', phone_code: '687', phoneLength: 6 },
    { code: 'NE', label: 'Niger', phone_code: '227', phoneLength: 8 },
    { code: 'NF', label: 'Norfolk Island', phone_code: '672', phoneLength: 6 },
    { code: 'NG', label: 'Nigeria', phone_code: '234', phoneLength: 8 },
    { code: 'NI', label: 'Nicaragua', phone_code: '505', phoneLength: 8 },
    { code: 'NL', label: 'Netherlands', phone_code: '31', phoneLength: 9 },
    { code: 'NO', label: 'Norway', phone_code: '47', phoneLength: 8 },
    { code: 'NP', label: 'Nepal', phone_code: '977', phoneLength: 10 },
    { code: 'NR', label: 'Nauru', phone_code: '674', phoneLength: 7 },
    { code: 'NU', label: 'Niue', phone_code: '683', phoneLength: 4 },
    { code: 'NZ', label: 'New Zealand', phone_code: '64', phoneLength: [8, 9] },
    { code: 'OM', label: 'Oman', phone_code: '968', phoneLength: 8 },
    { code: 'PA', label: 'Panama', phone_code: '507', phoneLength: 8 },
    { code: 'PE', label: 'Peru', phone_code: '51', phoneLength: 9 },
    { code: 'PF', label: 'French Polynesia', phone_code: '689', phoneLength: 8 },
    { code: 'PG', label: 'Papua New Guinea', phone_code: '675', phoneLength: 8 },
    { code: 'PH', label: 'Philippines', phone_code: '63', phoneLength: 10 },
    { code: 'PK', label: 'Pakistan', phone_code: '92', phoneLength: 10 },
    { code: 'PL', label: 'Poland', phone_code: '48', phoneLength: 9 },
    { code: 'PM', label: 'Saint Pierre and Miquelon', phone_code: '508', phoneLength: 6 },
    { code: 'PN', label: 'Pitcairn', phone_code: '870', phoneLength: 9 },
    { code: 'PR', label: 'Puerto Rico', phone_code: '1', phoneLength: 10 },
    { code: 'PS', label: 'Palestine, State of', phone_code: '970', phoneLength: 9 },
    { code: 'PT', label: 'Portugal', phone_code: '351', phoneLength: 9 },
    { code: 'PW', label: 'Palau', phone_code: '680', phoneLength: 7 },
    { code: 'PY', label: 'Paraguay', phone_code: '595', phoneLength: 9 },
    { code: 'QA', label: 'Qatar', phone_code: '974', phoneLength: 8 },
    { code: 'RE', label: 'Reunion', phone_code: '262', phoneLength: 10 },
    { code: 'RO', label: 'Romania', phone_code: '40', phoneLength: 10 },
    { code: 'RS', label: 'Serbia', phone_code: '381', phoneLength: 9 },
    { code: 'RU', label: 'Russian Federation', phone_code: '7', phoneLength: 10 },
    { code: 'RW', label: 'Rwanda', phone_code: '250', phoneLength: 9 },
    { code: 'SA', label: 'Saudi Arabia', phone_code: '966', phoneLength: 9 },
    { code: 'SB', label: 'Solomon Islands', phone_code: '677', phoneLength: 7 },
    { code: 'SC', label: 'Seychelles', phone_code: '248', phoneLength: 7 },
    { code: 'SD', label: 'Sudan', phone_code: '249', phoneLength: 7 },
    { code: 'SE', label: 'Sweden', phone_code: '46', phoneLength: 7 },
    { code: 'SG', label: 'Singapore', phone_code: '65', phoneLength: 8 },
    { code: 'SH', label: 'Saint Helena', phone_code: '290', phoneLength: 4 },
    { code: 'SI', label: 'Slovenia', phone_code: '386', phoneLength: 9 },
    { code: 'SJ', label: 'Svalbard and Jan Mayen', phone_code: '47', phoneLength: 8 },
    { code: 'SK', label: 'Slovakia', phone_code: '421', phoneLength: 9 },
    { code: 'SL', label: 'Sierra Leone', phone_code: '232', phoneLength: 8 },
    { code: 'SM', label: 'San Marino', phone_code: '378', phoneLength: 10 },
    { code: 'SN', label: 'Senegal', phone_code: '221', phoneLength: 9 },
    { code: 'SO', label: 'Somalia', phone_code: '252', phoneLength: [8, 9] },
    { code: 'SR', label: 'Suriname', phone_code: '597', phoneLength: [6, 7] },
    { code: 'SS', label: 'South Sudan', phone_code: '211', phoneLength: 7 },
    { code: 'ST', label: 'Sao Tome and Principe', phone_code: '239', phoneLength: 7 },
    { code: 'SV', label: 'El Salvador', phone_code: '503', phoneLength: 8 },
    { code: 'SX', label: 'Sint Maarten (Dutch part)', phone_code: '1-721', phoneLength: 10 },
    { code: 'SY', label: 'Syrian Arab Republic', phone_code: '963', phoneLength: 7 },
    { code: 'SZ', label: 'Swaziland', phone_code: '268', phoneLength: 8 },
    { code: 'TC', label: 'Turks and Caicos Islands', phone_code: '1-649', phoneLength: 10 },
    { code: 'TD', label: 'Chad', phone_code: '235', phoneLength: 6 },
    { code: 'TF', label: 'French Southern Territories', phone_code: '262', phoneLength: 10 },
    { code: 'TG', label: 'Togo', phone_code: '228', phoneLength: 8 },
    { code: 'TH', label: 'Thailand', phone_code: '66', phoneLength: 9 },
    { code: 'TJ', label: 'Tajikistan', phone_code: '992', phoneLength: 9 },
    { code: 'TK', label: 'Tokelau', phone_code: '690', phoneLength: 5 },
    { code: 'TL', label: 'Timor-Leste', phone_code: '670', phoneLength: 7 },
    { code: 'TM', label: 'Turkmenistan', phone_code: '993', phoneLength: 8 },
    { code: 'TN', label: 'Tunisia', phone_code: '216', phoneLength: 8 },
    { code: 'TO', label: 'Tonga', phone_code: '676', phoneLength: 5 },
    { code: 'TR', label: 'Turkey', phone_code: '90', phoneLength: 11 },
    { code: 'TT', label: 'Trinidad and Tobago', phone_code: '1-868', phoneLength: 7 },
    { code: 'TV', label: 'Tuvalu', phone_code: '688', phoneLength: 5 },
    { code: 'TW', label: 'Taiwan, Province of China', phone_code: '886', phoneLength: 9 },
    { code: 'TZ', label: 'United Republic of Tanzania', phone_code: '255', phoneLength: 7 },
    { code: 'UA', label: 'Ukraine', phone_code: '380', phoneLength: 9 },
    { code: 'UG', label: 'Uganda', phone_code: '256', phoneLength: 7 },
    { code: 'US', label: 'United States', phone_code: '1', phoneLength: 10 },
    { code: 'UY', label: 'Uruguay', phone_code: '598', phoneLength: 8 },
    { code: 'UZ', label: 'Uzbekistan', phone_code: '998', phoneLength: 9 },
    { code: 'VA', label: 'Holy See (Vatican City State)', phone_code: '379', phoneLength: 10 },
    { code: 'VC', label: 'Saint Vincent and the Grenadines', phone_code: '1-784', phoneLength: 7 },
    { code: 'VE', label: 'Venezuela', phone_code: '58', phoneLength: 7 },
    { code: 'VG', label: 'British Virgin Islands', phone_code: '1-284', phoneLength: 7 },
    { code: 'VI', label: 'US Virgin Islands', phone_code: '1-340', phoneLength: 10 },
    { code: 'VN', label: 'Vietnam', phone_code: '84', phoneLength: 9 },
    { code: 'VU', label: 'Vanuatu', phone_code: '678', phoneLength: 5 },
    { code: 'WF', label: 'Wallis and Futuna', phone_code: '681', phoneLength: 6 },
    { code: 'WS', label: 'Samoa', phone_code: '685', phoneLength: [5, 6, 7] },
    { code: 'XK', label: 'Kosovo', phone_code: '383', phoneLength: 8 },
    { code: 'YE', label: 'Yemen', phone_code: '967', phoneLength: 9 },
    { code: 'YT', label: 'Mayotte', phone_code: '262', phoneLength: 9 },
    { code: 'ZA', label: 'South Africa', phone_code: '27', phoneLength: 9 },
    { code: 'ZM', label: 'Zambia', phone_code: '260', phoneLength: 9 },
    { code: 'ZW', label: 'Zimbabwe', phone_code: '263', phoneLength: 9 },
];

export const get_country_map = (): CountryPhoneCodeMap => {
    let country_map: CountryPhoneCodeMap = {}
    countries.forEach((country: CountryProp) => {
        country_map[country.code] = {
            ...country,
            phoneLength: country.phoneLength ? country.phoneLength : 0,
            min: country.min ? country.min + country.phone_code.length : undefined,
            max: country.max ? country.max + country.phone_code.length : undefined
        }
    })
    return country_map
}


export default countries;