import { INITIAL_RECIPIENT, INITIAL_SENDER } from "../person/store";
import { Post, PostStatus, PostType } from "./types";

export const initialPost: Post = {
  id: 0,
  description: "",
  height: 3,
  length: 4,
  width: 6,
  step: "1",
  type: PostType["DOMESTIC"],
  status: PostStatus["ACTIVE"],
  weight: -1,
  barcode: "",
  weight_upper: 0,
  weight_lower: 0,
  service_id: 1,
  service_item_id: 1,
  zone: "",
  created_at: "",
  updated_at: "",
  country: "",
  service_bn_name: "",
  service_name: "",
  zone_id: 0,
  country_id: 0,
  service_cost: 5,
  additional_service_cost: 0,
  additional_service_items: [
    {
      id: 1,
      post_id: 0,
      additional_service_id: 1,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      created_at: '',
      name: 'registry',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 2,
      post_id: 0,
      additional_service_id: 2,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'gep',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 3,
      post_id: 0,
      additional_service_id: 3,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'ad_pod',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 4,
      post_id: 0,
      additional_service_id: 4,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'insurance',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 5,
      post_id: 0,
      additional_service_id: 5,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'international_insurance',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 6,
      post_id: 0,
      additional_service_id: 6,
      status_active: 0,
      is_delete: 0,
      cost: '1.00',
      value: '0',
      name: 'electronic_charge',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: true
    },
    {
      id: 7,
      post_id: 0,
      additional_service_id: 7,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'vat',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 8,
      post_id: 0,
      additional_service_id: 8,
      status_active: 0,
      is_delete: 0,
      cost: '100',
      value: '0',
      name: 'international_registry',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 9,
      post_id: 0,
      additional_service_id: 9,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'air_surcharge',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },


    {
      id: 10,
      post_id: 0,
      additional_service_id: 10,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'vp',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 11,
      post_id: 0,
      additional_service_id: 11,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'blind_literature',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },
    {
      id: 12,
      post_id: 0,
      additional_service_id: 12,
      status_active: 0,
      is_delete: 0,
      cost: '0',
      value: '0',
      name: 'postal_service',
      created_at: '',
      updated_at: '',
      selectable: true,
      selected: false
    },

  ],
  created_by: 1,
  total_cost: 1,
  sender: INITIAL_SENDER,
  recipient: INITIAL_RECIPIENT,
}






